sudo: false
language: go
go:
  - 1.10.2
go_import_path: github.com/cofyc/kubelet-exporter
install: true
script:
  - go get github.com/golang/dep/cmd/dep
  - dep ensure -v -vendor-only
  - go test -timeout 5m github.com/cofyc/kubelet-exporter/...
  - go install github.com/cofyc/kubelet-exporter/cmd/kubelet-exporter
